FROM node:16-alpine

WORKDIR /app

# Kopiujemy pliki package.json i package-lock.json
COPY package*.json ./

# Instalujemy zależności
RUN npm install

# Nie kopiujemy kodu źródłowego - będzie on montowany przez volume
# COPY . .

# Ustawiamy port dla React development servera
EXPOSE 3000

# Uruchamiamy aplikację w trybie development
CMD ["npm", "start"] 